### ISSUE TITLE
does not display errors

### ISSUE THREAD

**Issue by starynights** [saeedsltm/FDSNW-GUI#1]
I'm requesting waveform but always getting "Operations failed ! Please check your entries". Could you please display what field is wrong ?
![error](https://user-images.githubusercontent.com/89962206/131789525-7c052733-c500-4b15-b8f7-2067ef68fb8e.png)

**Comment by saeedsltm** [comment]
Dear @starynights when requesting waveform you should specify a directory name not a file name. so if you choose a directory for saving results, your problem will be solved as i tried it and it worked. BTW, i will add a dialog box for reporting which part of request encountered with problem. thanks for your suggestion :)

![Screenshot from 2021-09-02 11-05-40](https://user-images.githubusercontent.com/20725501/131795099-920ef590-9316-4e91-8025-6a70c6b0d107.png)

**Comment by starynights** [comment]
Thanks for further improvement. Issue was with Date/Time picker. It was picking 2121 instead of 2021. You may consider displaying the 4 digits year and changing the time to 0-24 UTC rather the AM/PM. You may also consider adding a scroll bar in error display area, so user can track down the error. Currently, error disappear shortly after the display.
Thank you for the development.
